changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Gameplay changes
      labels:
        - gameplay
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Compatibility and internals
      labels:
        - compatibility
        - refactor
        - build
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
