# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.installations.paths=C:/Program Files/Microsoft/jdk-25.0.2.10-hotspot

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.teddante.emergent
archives_base_name=emergent

# Dependencies
fabric_api_version=0.146.1+26.1.2
modmenu_version=18.0.0-alpha.8
cloth_config_version=26.1.154
